require("modules.monitors")
require("modules.binds")
require("modules.autostart")
require("modules.env")
require("modules.decoration")
require("modules.layout")
require("modules.windowrules")
require("modules.misc")
require("modules.input")

hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")